### ISSUE TITLE
DI полей

### ISSUE THREAD

**Issue by das13** [ValentynChepiha/NCProjectEShop#13]
В Spring не рекомендуется использовать DI полей:
ApiController
BrandController
BrandRepository
ClientController
ClientRepository
LocationController
LocationRepository
OrderController
OrderProductRepository
OrderRepository
ParseRequestApiService
ProductController
ProductRepository
ProductToOnlineRepository
SecurityConfig
StorageController
StorageRepository
UserController
UserRepository
UserRoleRepository

**Comment by ValentynChepiha** [comment]
done
