### ISSUE TITLE
Правильное DI

### ISSUE THREAD

**Issue by das13** [ValentynChepiha/NCProjectEShop#3]
Заменить классы на интерфейсы при DI. Например:
`private BrandRepository brandRepository;`
на
`private ModelRepository<Brand> brandRepository;`

**Comment by ValentynChepiha** [comment]
Поміняв  3375f7288de1499a9b3e6a2cd1763eed5a2a9440

**Comment by ValentynChepiha** [comment]
Пересмотрел код.
Внес исправления в сервисы b06bf8218e77c500f3ac495d46f4772c12febe3b
