### ISSUE TITLE
Сеовисы

### ISSUE THREAD

**Issue by das13** [ValentynChepiha/NCProjectEShop#9]
Классы
LoggerMsgService
ListEqualsService
ValidateService
сервисами Spring не являются, т.к. у них отсутствует соответствующая аннотация.
Нужно переименовать классы. Или (предпочтительнее) добавить аннотацию @Service и использовать для них DI

**Comment by ValentynChepiha** [comment]
ListEqualsService +
ValidateService +
LoggerMsgService  -> LoggerMsg

**Comment by ValentynChepiha** [comment]
ListEqualsService  -> EqualListsOrderProduct: метод static compare

**Comment by ValentynChepiha** [comment]
ValidateService -> ValidateString

**Comment by ValentynChepiha** [comment]
Done 71e25cae50cf3d79a5961758a17df956d7e145a4
